[build]
  # This is the directory to change to before starting a build.
  base    = "./src/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = ""
  # This will be your default build command
  command = "npm run start"
  # Ignore build command if exit 0
  ignore = "git diff --quiet HEAD^ HEAD sub_dir/"
  # If skip_processing = true, all other settings are ignored
  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = true
    minify = false
  [build.processing.js]
    bundle = true
    minify = false
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true